name: Update Website Content

on:
  repository_dispatch:   
  workflow_dispatch:  

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: sre-app-token
        with:
          app-id: ${{ secrets.CDS_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.CDS_RELEASE_BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install dependencies
        run: npm install

      - name: Run PR Bot with Monitoring
        run: node index.js
        env:
          TOKEN: ${{ steps.sre-app-token.outputs.token }}
          GC_ARTICLES_ENDPOINT_EN: https://articles.alpha.canada.ca/cds-snc/wp-json/wp/v2/
          GC_ARTICLES_ENDPOINT_FR: https://articles.alpha.canada.ca/cds-snc/fr/wp-json/wp/v2/
          NODE_ENV: Production